# Generated by Django 3.2.6 on 2021-08-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210816_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commet',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commet', to='article.article', verbose_name='commett'),
        ),
    ]
