# Generated by Django 3.2.6 on 2021-08-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_commet_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-createdDate']},
        ),
        migrations.AlterModelOptions(
            name='commet',
            options={'ordering': ['-createDate']},
        ),
    ]
